### ISSUE TITLE
Friendlier message when not configured

### ISSUE THREAD

**Issue by pop4959** [ParadauxIO/HiberniaDiscord#7]
On first launch (to generate the config), the following error is printed. Might be nice to replace it with a friendlier message when the plugin hasn't been configured yet so that people don't think the plugin is broken.

```
[17:29:37 ERROR]: Could not pass event ServerLoadEvent to HiberniaDiscord v3.0.1
java.lang.IllegalArgumentException: Failed to parse webhook URL
        at club.minnced.discord.webhook.WebhookClientBuilder.<init>(WebhookClientBuilder.java:86) ~[?:?]
        at io.paradaux.hiberniadiscord.WebhookUtils.GenericWebhook.createClient(GenericWebhook.java:52) ~[?:?]
        at io.paradaux.hiberniadiscord.WebhookUtils.GenericWebhook.<init>(GenericWebhook.java:44) ~[?:?]
        at io.paradaux.hiberniadiscord.WebhookUtils.ChatWebhook.<init>(ChatWebhook.java:11) ~[?:?]
        at io.paradaux.hiberniadiscord.EventListeners.ServerLoadEventListener.Listener(ServerLoadEventListener.java:39) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-261]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[17:29:37 ERROR]: Could not pass event ServerLoadEvent to HiberniaDiscord v3.0.1
java.lang.IllegalArgumentException: Failed to parse webhook URL
        at club.minnced.discord.webhook.WebhookClientBuilder.<init>(WebhookClientBuilder.java:86) ~[?:?]
        at io.paradaux.hiberniadiscord.WebhookUtils.GenericWebhook.createClient(GenericWebhook.java:52) ~[?:?]
        at io.paradaux.hiberniadiscord.WebhookUtils.GenericWebhook.<init>(GenericWebhook.java:44) ~[?:?]
        at io.paradaux.hiberniadiscord.WebhookUtils.ChatWebhook.<init>(ChatWebhook.java:11) ~[?:?]
        at io.paradaux.hiberniadiscord.EventListeners.ServerStopEventListener.Listener(ServerStopEventListener.java:38) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor26.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-261]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```

**Comment by ParadauxIO** [comment]
I didn't realise that was an issue from my limited testing -- Will fix shortly

**Comment by pop4959** [comment]
That's generally how it is. Just wanted to let you know so you don't get hit by another 1 star review by someone who doesn't know better.

After configuring the web hook the plugin works perfectly.
